### ISSUE TITLE
Reporting multiple errors

### ISSUE THREAD

**Issue by Kyuuhachi** [yaahc/color-eyre#108]
In some cases it might be useful to bundle several errors into one, displaying them all together. A few prior example are Python's [PEP 654](https://peps.python.org/pep-0654/), Trio's [MultiError](https://trio.readthedocs.io/en/stable/reference-core.html#working-with-multierrors) (which inspired the former), and Haskell's [Validate monad](https://hackage.haskell.org/package/monad-validate-1.2.0.0/docs/Control-Monad-Validate.html). Would something like that be possible and/or reasonable to add? Asking here rather than `eyre` because `section` is here, so it feels appropriate.

I can get a mediocre implementation by doing
```rs
	use std::fmt::Write;
	use color_eyre::{Section, SectionExt};
	match errors.len() {
		0 => Ok(result),
		1 => Err(errors.pop().unwrap()),
		_ => Err(eyre::eyre!("Multiple errors").section({
			let mut s = String::new();
			for e in errors {
				write!(s, "{:?}", e).unwrap();
			}
			s.header("Errors:")
		})),
	}
```
, but the formatting is pretty bad and contains much duplication; in particular, trimming off the shared tail of the backtraces would make it much better.

**Comment by yaahc** [comment]
This should already be supported: https://github.com/yaahc/color-eyre/blob/master/examples/multiple_errors.rs
