### ISSUE TITLE
RUST_BACKTRACE=1 and RUST_LIB_BACKTRACE=0 not respected

### ISSUE THREAD

**Issue by Lej77** [yaahc/color-eyre#11]
I was testing out this crate and noticed that the environment variable combination `RUST_BACKTRACE=1` and `RUST_LIB_BACKTRACE=0` still causes backtraces to be printed from errors. The readme for the `eyre` crate mentions that "If you want only panics to have backtraces, set RUST_BACKTRACE=1 and RUST_LIB_BACKTRACE=0." Of course that only applies if you use the nightly backtrace implementation but I assume that this crate should support it as well.

**Comment by yaahc** [comment]
Thank you for this bug report!

I've gone and vendored the exact logic that std uses when its capturing the `std::backtrace::Backtrace` type and added additional doc tests to the `Context` type to document and test the exact behavior of backtrace capture. As an added bonus I improved the documentation about when we do and don't capture `SpanTrace`s. All of this is in PR #14, please let me know if there are any issues still.

**Comment by Lej77** [comment]
Thank you! I really like how this crate presents errors, it feels so much better than the plain output of alternative error crates!
