### ISSUE TITLE
Colored text is really dark on windows

### ISSUE THREAD

**Issue by Lej77** [yaahc/color-eyre#12]
The colored text is quite dark on windows which makes it hard to read. It should probably use the same colors as `rustc` since those colors are well tested. `rustc` seems to set its colors in [`rust/src/librustc_errors/emitter.rs` at line 2061](https://github.com/rust-lang/rust/blob/584252bfb053149b1405da0951cd855561694990/src/librustc_errors/emitter.rs#L2063-L2099) and in [`rust/src/librustc_errors/lib.rs` at line 957](https://github.com/rust-lang/rust/blob/b7bd7c1024a1449449c3ae7b4b4c63a904a620e6/src/librustc_errors/lib.rs#L961-L970). 

The difference seems to be that `rustc` is using "intense" colors instead of the normal ones. `rustc` is using the [`termcolor`](https://crates.io/crates/termcolor) crate to handle terminal text color and unfortunately [`ansi_term`](https://crates.io/crates/ansi_term) doesn't offer a simple way to make colors more intense. We also can't switch to `termcolor` since that crate can't be used to color text that is written via `std::fmt::Debug`. But I think converting a color to its intense variant can be done using something like:

```rust
trait ColorExt {
    fn make_intense(self, doit: bool) -> Self;
}
impl ColorExt for ansi_term::Color {
    fn make_intense(self, doit: bool) -> Self {
        use ansi_term::Color::*;

        if doit {
            match self {
                Black => Fixed(8),
                Red => Fixed(9),
                Green => Fixed(10),
                Yellow => Fixed(11),
                Blue => Fixed(12),
                Purple => Fixed(13),
                Cyan => Fixed(14),
                White => Fixed(15),
                Fixed(color) if color < 8 => Fixed(color + 8),
                other => other,
            }
        } else {
            self
        }
    }
}
impl ColorExt for ansi_term::Style {
    fn make_intense(mut self, doit: bool) -> Self {
        if let Some(color) = self.foreground {
            self.foreground = Some(color.make_intense(doit));
        }
        self
    }
}
```

And then just call `make_intense(true)` on any color before using it to print something. From my simple testing this results in the same colors as `rustc` is using. Also if you want to only do this for windows you can just do `make_intense(cfg!(windows))` instead.

**Comment by yaahc** [comment]
I think it might make sense to try to get this fixed in `ansi_term`. Let's try opening an issue upstream, it ends up taking too long to get it merged / released up stream we can temporarily fix it here and in `color-spantrace` but I'd prefer to not duplicate code across crates if possible.

**Comment by Lej77** [comment]
That sounds like a good idea! Don't know how robust this code is though, but if it has issues then they should probably be able to offer feedback!

**Comment by yaahc** [comment]
Here we go https://github.com/ogham/rust-ansi-term/pull/67

**Comment by Lej77** [comment]
Seems good! What about fixed colors that are affected (the `Fixed(color) if color < 8 => Fixed(color + 8),` match arm in my example code)?

**Comment by yaahc** [comment]
oo, good catch

**Comment by Lej77** [comment]
You could probably simplify the `Colour::intense` to `Style { foreground: Some(self), .. Style::default() }.intense()` to re use code.

**Comment by yaahc** [comment]
Since there has been no movement on this upstream I'm fixing this issue locally in color-spantrace and color-eyre. I'll get out a new release with the fixed coloring shortly.

**Comment by Lej77** [comment]
Okay, that seems reasonable! Will be nice to get some better colors for my error messages.

**Comment by yaahc** [comment]
should be good, try out `0.3.4` and lmk how it goes

**Comment by Lej77** [comment]
I tested the new version and it looks a lot better now, thanks!
