### ISSUE TITLE
Compile error when returning result of `eyre!` macro as `color_eyre::Result`

### ISSUE THREAD

**Issue by tinkerware** [yaahc/color-eyre#26]
The code below fails to compile:

```rust
use std::num::ParseIntError;
use color_eyre::Result;
use eyre::eyre;

fn parse(s: &str) -> Result<i32, ParseIntError> {
    return s.parse::<i32>();
}

fn main() -> Result<()> {
    match parse("abc") {
        Ok(n) => Ok(()),
        Err(e) => Err(eyre!(e).wrap_err("try parsing an actual number")),
    }
}
```

with the following error:

```
error[E0308]: mismatched types
  --> example.rs:12:23
   |
12 |         Err(e) => Err(eyre!(e).wrap_err("try parsing an actual number")),
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `color_eyre::Handler`, found struct `eyre::DefaultHandler`
   |
   = note: expected struct `eyre::Report<color_eyre::Handler>`
              found struct `eyre::Report<eyre::DefaultHandler>`

error: aborting due to previous error
```

It seems to me that the dispatch machinery in `eyre::kind` module can't deal with different handlers other than the default one, so maybe the issue belongs there, but I ran into this when playing with `color_eyre`(which I really like, by the way). The example is a bit contrived, and I'm not sure if I'm doing something I'm not supposed to. What do you think?

**Comment by yaahc** [comment]
oh shit, yea it looks like it needs to have a generic added to the trait because right now its immediately resolving it to the locally defined context type. I'll get that fixed up and push a new release tomorrow

**Comment by yaahc** [comment]
Oh, btw. Short term if you want a way to work around this error the `eyre!` call in this example isn't necessary, instead you can write this.

```rust
use std::num::ParseIntError;
use color_eyre::Result;
use eyre::{eyre, WrapErr};

fn parse(s: &str) -> Result<i32, ParseIntError> {
    return s.parse::<i32>();
}

fn main() -> Result<()> {
    parse("abc").wrap_err("try parsing an actual number)
}
```
