### ISSUE TITLE
Disabling warning message for SpanTrace capture

### ISSUE THREAD

**Issue by SecurityInsanity** [yaahc/color-eyre#32]
Hey :wave:  Thanks for the great library!

After installing tracing without adding in a `ErrorLayer::default()` (since that prints span traces which I _don't want_), even when returning an error from a main function I see a note about:

```
Warning: SpanTrace capture is Unsupported.
Ensure that you've setup an error layer and the versions match
```

Specifically a full error message looks like:

```text
$  ../../../target/dl
Error: 
   0: Failed to parse as yaml

 --> .dl/dl-tasks.yml:1:11
  |
...
3 |   - type: ppipeline
  |           ^ tasks[0].type: unknown variant `ppipeline`, expected one of `command`, `oneof`, `pipeline`, `parallel-pipeline` at line 3 column 11
  |

Warning: SpanTrace capture is Unsupported.
Ensure that you've setup an error layer and the versions match

Suggestion: Instead of: "ppipeline", Did you mean: "pipeline"
Note: Full types, and supported values are documented at: https://dev-loop.kungfury.io/docs/schemas/task-conf-file
```

Is there anyway to remove that: `warning: SpanTrace capture is Unsupported` message? I've specifically set it up this way because I don't want span traces captured unless a user is specifically asking for it. As for most users of this binary it won't actually be useful (and serve to confuse potential users who don't understand, and shouldn't have to understand the internals of the tool).

**Comment by yaahc** [comment]
if you're not compiling with an error layer it's probably safe to just disable all the tracing support with `default-features = false`. that should hopefully disable the warning

**Comment by SecurityInsanity** [comment]
Thanks, it's good to know it is a compile time flag. Unfortunately the problem is I do want span traces some of the time, and ideally I'd like to distribute it to users as such (right now I've been adding it if `RUST_BACKTRACE` or `RUST_LIB_BACKTRACE` is present in the environment).

There are some cases where it is incredibly useful, just not the default. I can imagine a couple issues where I might ask a user for a span trace, but in the case of the example above (a user typo'd a piece of config) it's just not useful there?

**Comment by yaahc** [comment]
Oh okay. I think the solution is just to add some check of an env variable before capturing SpanTraces when constructing Reports. If the error layer isn't setup but the SpanTrace is None it should not print the warning.

I think I'd still prefer to default to capturing SpanTraces, so it would only not capture them if the `RUST_SPANTRACE` variable is defined and set to 0. You would need to explicitly check if the variable is unset on startup and set it to 0 with `std::env::set_var`, would this work for you?

**Comment by SecurityInsanity** [comment]
Yep! That'd be more than fine.
