### ISSUE TITLE
Colors and suggestions missing without default-features

### ISSUE THREAD

**Issue by Ninjani** [yaahc/color-eyre#36]
Hi!
I tried upgrading `eyre` (0.5 -> 0.6) and `color_eyre` (0.4.1 -> 0.5) and error messages are no longer colored and don't show suggestions.

with:
```
eyre = "0.6.0"
color-eyre = { version = "0.5.0", default-features = false }
``` 

Looks like it could be because the `color_backtrace` dependency is gone? Is there a change in syntax?

**Comment by yaahc** [comment]
The newest version of `eyre` and its related libraries requires you to install an error report hook. You probably just need to add a call to `install` in main.

```rust
fn main() -> Result<()> {
    color_eyre::install()?;
    ...
}
```

**Comment by Ninjani** [comment]
Ah, that fixed it. Thanks!
