### ISSUE TITLE
Support for WASM: Add CI for `wasm32-unknown-unknown`

### ISSUE THREAD

**Issue by SecurityInsanity** [yaahc/color-eyre#37]
👋 ,

We have a particular use case that involves deploying to a WASM target, and although the crate seems to build fine with WASM, and work it'd be nice to have continuous integration running on this project that confirms all is working okay as time goes on. FWIW tracing is currently in the same boat: https://github.com/tokio-rs/tracing/issues/642

**Comment by SecurityInsanity** [comment]
Also we'd be happy to work on the wasm side of things if you'd like, do any testing/validation. I just really wanna get a feeling check making sure this is okay to do. 😄

**Comment by yaahc** [comment]
I am 100% on board with adding wasm to CI, especially if you're already happy to contribute the changes needed.
