### ISSUE TITLE
Breaking change in 0.2.3

### ISSUE THREAD

**Issue by dtolnay** [yaahc/color-eyre#5]
This program works with color-eyre 0.2.2 but fails to compile with 0.2.3.

```rust
// [dependencies]
// color-eyre = "0.2"
// eyre = "0.3"

use color_eyre::Report;
use eyre::WrapErr;

fn main() -> Result<(), Report> {
    Ok::<(), Report>(()).wrap_err("...")
}
```

**Comment by yaahc** [comment]
Shit, I was hoping that wouldn't be a breaking change. It has been yanked, I'll publish a new version in a minute.

**Comment by dtolnay** [comment]
Removing support for a dependency that appears in the public API (eyre 0.3, via trait impls) is a breaking change.
