### ISSUE TITLE
Custom message in panic hook

### ISSUE THREAD

**Issue by Stupremee** [yaahc/color-eyre#50]
I would like to add a message like `please report the but on github (https://github.com/...)` to the panic hook.
I suggest adding a `panic_note` method to `HookBuilder` that will just be inserted after the message.

```rust
The application panicked (crashed).
Message:  No such file or directory (os error 2)
Location: examples/panic_hook.rs:39

Consider reporting the bug on github (https://github.com/yaahc/color-eyre)

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by yaahc** [comment]
great idea

**Comment by Stupremee** [comment]
Then I'm ready to open a PR because I already have the changes in my fork :+1:

**Comment by yaahc** [comment]
That would be great! thank you very much
