### ISSUE TITLE
Ability to silence `Backtrace omitted.` Error Messaging

### ISSUE THREAD

**Issue by SecurityInsanity** [yaahc/color-eyre#65]
Hey again,

Similar to my issue for: https://github.com/yaahc/color-eyre/issues/32 , it seems color-eyre has started adding in messages about the fact that backtraces are not being captured, compare a message just using 0.5.0:

![Old Dev-Loop Error](https://user-images.githubusercontent.com/7262714/87958108-5d5fe380-ca6e-11ea-899f-65201e3e0c97.png)

With one using 0.5.5:

![Screenshot from 2020-09-23 10-09-30](https://user-images.githubusercontent.com/7262714/94039380-e5bb7700-fd84-11ea-8e55-09fdef892be5.png)

This adds a lot of noise, even more so when there may be multiple errors printed to the screen (since they're "recoverable" cases):

![Screenshot from 2020-09-23 10-11-52](https://user-images.githubusercontent.com/7262714/94039687-43e85a00-fd85-11ea-8061-935a802c99a8.png)

All this extra lines can make it hard to zero in on what's important, even more so when it's repeated multiple times. Is there any chance similar to the capture spantrace message being able to be turned off with some: `capture_span_trace_by_default` we could get an option for disabling the backtrace output as well?

**Comment by yaahc** [comment]
no need, I added this around a month ago

https://docs.rs/color-eyre/0.5.5/color_eyre/config/struct.HookBuilder.html#method.display_env_section

**Comment by SecurityInsanity** [comment]
Ah I thought I checked and everything! So sorry for missing that. Thank you so much!

**Comment by yaahc** [comment]
No worries at all :D
