### ISSUE TITLE
Improve the error message for a lacking error-layer to better explain how to setup tracing_error

### ISSUE THREAD

**Issue by yaahc** [yaahc/color-eyre#74]
I know it's unrelated to this PR, but I found this message confusing when I first encountered it. Perhaps some guidance as to how to "setup an error layer", and what exactly an "error layer" is would be helpful to users who are unfamiliar with the ecosystem.

_Originally posted by @kellpossible in https://github.com/yaahc/color-eyre/pull/67#discussion_r496487180_

**Comment by kellpossible** [comment]
ran into this issue again with a new project :sweat_smile:

**Comment by yaahc** [comment]
oof, ill try to get this fixed asap then.
