### ISSUE TITLE
Doc comments still reference `Help` trait instead of `Section` trait

### ISSUE THREAD

**Issue by lilyball** [yaahc/color-eyre#86]
The `src/lib.rs` module doc comment still talks about the `Help` trait instead of the `Section` trait, and a bunch of example code in doc comments still import `color_eyre::Help`.

https://github.com/yaahc/color-eyre/blob/472997e9d6911452876032c0db1f9601c70fd91a/src/lib.rs#L224
https://github.com/yaahc/color-eyre/blob/472997e9d6911452876032c0db1f9601c70fd91a/src/lib.rs#L303-L305
https://github.com/yaahc/color-eyre/blob/472997e9d6911452876032c0db1f9601c70fd91a/src/lib.rs#L233
(and 8 more example code references in `src/section/mod.rs`)

This is very confusing given that the `color_eyre::Help` re-export is marked as `#[doc(hidden)]`, and the hyperlink to the `Help` trait docs is both broken and not clickable in the `cargo doc`/docs.rs rendering anyway. I couldn't figure out what this was talking about until I read through the source to find the hidden re-export

https://github.com/yaahc/color-eyre/blob/472997e9d6911452876032c0db1f9601c70fd91a/src/lib.rs#L373-L374

**Comment by lilyball** [comment]
`eyre` also [still references](https://docs.rs/eyre/0.6.5/eyre/) the old `Help` trait in its crate docs.

**Comment by lilyball** [comment]
Bizarrely, `jane-eyre` actually contains its own [definition of the `Help` trait](https://github.com/yaahc/jane-eyre/blob/8d153d72f483fdd6b6834ffb8e9196e3735f193a/src/help.rs).

**Comment by yaahc** [comment]
> Bizarrely, `jane-eyre` actually contains its own [definition of the `Help` trait](https://github.com/yaahc/jane-eyre/blob/8d153d72f483fdd6b6834ffb8e9196e3735f193a/src/help.rs).

loool, looks like I forgot to delete the file, iirc color-eyre was what I renamed jane-eyre to

**Comment by yaahc** [comment]
Ty for letting me know about these, I'll clean them up tomorrow, or if you wanted to send a PR cleaning them too up I'd be eternally grateful.
