### ISSUE TITLE
Only log when an environment variable is present

### ISSUE THREAD

**Issue by Bobbbay** [yaahc/color-eyre#88]
Hi everyone!

Basically, I'd like to only log when an environment variable is present. Else, just print out the stderr and call it a day. I'm currently writing a parser, that uses `ariadne` to pretty-print errors on files. Currently, my code for Eyre looks like this:

```
fn setup() -> Result<()> {
    if std::env::var("SALO_LOG").is_ok() {
        if std::env::var("RUST_BACKTRACE").is_err() {
            std::env::set_var("RUST_BACKTRACE", "1")
        }
        color_eyre::install()?;
    }

    Ok(())
}
```

When the parser is given code that it deems invalid, it outputs this:

```
Error: Error
    ╭─[<unknown>:3:1]
    │
  3 │ a        2 - 1;
    · ┬
    · ╰── Unexpected character
────╯
Error: A

Location:
    /rustc/35fff69d043b1c0f5c29894e7f4b0da8b039c131/library/core/src/convert/mod.rs:538:9
```

Which is great already - however, what I'd prefer to see as output is only this:

```
Error: Error
    ╭─[<unknown>:3:1]
    │
  3 │ a        2 - 1;
    · ┬
    · ╰── Unexpected character
────╯
```

i.e. omitting the Rust-specific information at the end. 

Unless... `SALO_LOG` is set (salo is the name of the project:)). In this case, I specifically want a backtrace of the error, all logs, etc.

Not sure if I'm asking in the right place, but some guidance would be awesome. Cheers 🍻

**Comment by yaahc** [comment]
https://docs.rs/color-eyre/0.5.11/color_eyre/config/struct.HookBuilder.html should have the necessary APIs you need to configure the hook differently depending on the env. You'll want to hide the env section and make a custom panic message. If there are any missing configuration options we can definitely add those.

**Comment by Bobbbay** [comment]
That was the one! Thank you, and cheers!

**Comment by yaahc** [comment]
> That was the one! Thank you, and cheers (sorry for wasting your time ;))!

No worries at all. It always makes me happy seeing actual users for my crates and what they're up to, and this gives me a good idea of where I can improve the docs.
