### ISSUE TITLE
the cat could not got be got

### ISSUE THREAD

**Issue by samusz** [yaahc/color-eyre#89]
Hi, 

in your RustConf you showed this example: `

fn main() -> Result<(), eyre::Report> {
    color_eyre::install()?;

    let _ = std::process::Command::new("git")
        .arg("cat")
        .output2()
        .wrap_err("The cat couldnot be got")?;

    Ok(())

}
`
But I couldn't get it to work. 

I tried different `use` statements but failed to get the `.output2()` working. 

Sorry if this issue isn't really one. Help much appreciated on this fun example.

**Comment by yaahc** [comment]
The `output2` method is from a trait that was being implemented during the talk as an example, not a trait that is part of `color-eyre`.
